# backend/docker-compose.yml
services:
  postgres-db:
      image: postgres:14-alpine  
      container_name: watch-tasks-db
      restart: always 
      environment:
        POSTGRES_USER: ${POSTGRES_USER} 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432" 
      volumes:
        - ./postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data: